name: nova
description: Nova Chat Messenger
publish_to: 'none'

version: 1.0.141

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  image_picker: ^1.0.0
  cached_network_image: ^3.2.0
  file_picker: ^5.2.0+1

  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.4
  photo_view: ^0.14.0
  contacts_service: ^0.6.3
  audioplayers: ^3.0.1
  flutter_countdown_timer: ^4.1.0
  permission_handler: ^10.2.0
  carousel_slider: ^4.1.1
  connectivity_plus: ^4.0.1
  linkable: ^3.0.1
  video_compress: ^3.1.0
  flutter_image_compress: ^2.0.3

  stop_watch_timer: ^2.0.0
  share_plus: ^6.3.4
  fluttertoast: ^8.0.9
  flutter_chat_bubble: ^2.0.2
  visibility_detector: ^0.4.0+2
  country_code_picker: ^3.0.0
  dynamic_themes: ^1.1.0
  flutter_slidable: ^0.6.0
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.2.0
  lottie: ^2.3.2
  flutter_vibrate: ^1.3.0
  font_awesome_flutter: ^10.1.0
  record: ^4.4.4
  just_audio: ^0.9.28
  phoenix_wings: ^1.0.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  supabase_flutter: ^1.10.7

  path_provider: ^2.0.15
  flutter_dotenv: ^5.0.2
  overlay_support: ^2.0.1
  flutter_walkthrough_screen:
  pin_code_fields: ^8.0.1
  webview_flutter: ^4.2.2
  encrypt: ^5.0.1
  agconnect_auth:
  device_info_plus: ^8.2.2
  flutter_spinkit: ^5.1.0
  flutter_markdown: ^0.6.9
  animations: ^2.0.1
  huawei_push: ^6.7.0+300
  just_audio_cache: ^0.1.1
  rsa_encrypt: ^2.0.0
  url_launcher: ^6.1.5
  pointycastle: ^3.6.1
  basic_utils: ^5.3.0
  uuid: ^3.0.6
  flutter_network_connectivity: ^0.0.6
  sentry_flutter: ^7.8.0
  sentry_logging: ^7.8.0
  dropdown_button2: ^2.1.4
  flutter_app_badger: ^1.5.0
  package_info_plus: ^3.1.2
  animated_text_kit: ^4.2.1
  #flutter_cached_pdfview: ^0.4.1
  easy_pdf_viewer: ^1.0.6
  loading_animation_widget: ^1.2.0+3
  flick_video_player: ^0.5.0
  flutter_easyloading: ^3.0.5
  chewie: ^1.5.0
  store_redirect: ^2.0.1
  amplitude_flutter: ^3.10.0
  flutter_local_notifications: ^15.0.1
  eraser: ^2.0.1
  video_thumbnail: ^0.5.3
  firebase_storage: ^11.2.4
  huawei_hmsavailability: ^6.6.0+300
  wakelock: ^0.6.2
  flutter_svg: ^2.0.5
  scrollable_positioned_list: ^0.3.5
  modal_progress_hud_nsn: ^0.4.0
  agconnect_core: ^1.6.0+300
  app_links: ^3.4.3
  voice_message_package: ^1.0.41
  audio_waveforms: ^1.0.4
  flutter_keyboard_visibility: ^5.4.1
  firebase_core: ^2.14.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  firebase_core_platform_interface: 4.8.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/applogo.png"
  image_path_ios: "assets/images/applogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/pem/
    - assets/walkthrough/
    - assets/audio/
    - data/
    - assets/vn/dustbin.json
    - assets/vn/dustbin_grey.json
    - .env

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-BoldItalic.ttf
        - asset: assets/fonts/DMSans-MediumItalic.ttf
        - asset: assets/fonts/DMSans-Italic.ttf

