// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHaAqyD0YCqPy5C7JvM4XgpVHXlB_NOX0',
    appId: '1:913016876917:android:6274acb985fd9e8326ed3c',
    messagingSenderId: '913016876917',
    projectId: 'novamessenger-61eab',
    storageBucket: 'novamessenger-61eab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDo36v-DiLX3GhKn3jhqiaYFvdQMjIfAY',
    appId: '1:913016876917:ios:643f4c07c0053bd426ed3c',
    messagingSenderId: '913016876917',
    projectId: 'novamessenger-61eab',
    storageBucket: 'novamessenger-61eab.appspot.com',
    androidClientId: '913016876917-27nuvkk19g90058fp9gc43k215e25bc5.apps.googleusercontent.com',
    iosClientId: '913016876917-k94dmpfacob0lccrugti3n2bsbl9mciv.apps.googleusercontent.com',
    iosBundleId: 'com.nova.messenger',
  );
}
